minio:
  endpoint: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: pdf-files

spring:
  application:
    name: conversion
  kafka:
    topics:
      file-update: file-update-topic
      file-upload: file-upload-topic
    bootstrap-servers: localhost:9092
    consumer:
      group-id: conversion-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
